version: '3'
services:
  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coamana-app
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
      - /var/www/vendor
      - ./tests:/var/www/tests
      - ./.env.testing:/var/www/.env.testing
    environment:
      - .env
    networks:
      - app-network      
    depends_on:
      - db1

  nginx:
    image: nginx:alpine
    container_name: web-browser
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network   
      
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: front-end
    container_name: front-end
    ports:
      - "3001:3001"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - app-network

  db1:
    image: mysql:latest
    container_name: coamana-mysql-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
